# NumPy Array Copy VS View - Difference

-In NumPy, when working with arrays, it's important to understand the difference between copy and view because they determine how modifications affect the original data. Let’s explore both concepts separately.


# Copy in NumPy Arrays

- A copy creates a completely new array with its own data. Any modifications to the copy do not affect the original array.

- A new memory location is allocated.

- Changes made to the copy do not reflect in the original array.

- Uses copy() method.

In [1]:
import numpy as np

# Original array
arr = np.array([1, 2, 3, 4, 5])

# Creating a copy of the array
arr_copy = arr.copy()

# Modifying the copied array
arr_copy[0] = 100

# Printing both arrays
print("Original Array:", arr)       # Output: [1 2 3 4 5] (unchanged)
print("Copied Array:", arr_copy)    # Output: [100 2 3 4 5] (modified)


Original Array: [1 2 3 4 5]
Copied Array: [100   2   3   4   5]


-arr_copy is a new independent array.

-Changing arr_copy[0] does not affect arr.


# View in NumPy Array

- A view is a new array object that shares the same data as the original array. Any modification made to the view also affects the original array and vice versa.

- No new memory is allocated for data.

- Changes in the view reflect in the original array.

- Uses view() method.

In [2]:
import numpy as np

# Original array
arr = np.array([10, 20, 30, 40, 50])

# Creating a view of the array
arr_view = arr.view()

# Modifying the view
arr_view[0] = 99

# Printing both arrays
print("Original Array:", arr)      # Output: [99 20 30 40 50] (changed)
print("View Array:", arr_view)     # Output: [99 20 30 40 50] (changed)


Original Array: [99 20 30 40 50]
View Array: [99 20 30 40 50]


- arr_view is a view of arr, meaning it references the same data.

- Changing arr_view[0] also changes arr[0].



# How to Check if an Array Owns Its Data?

- You can use the .base attribute to check if an array is a view or a copy.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_copy = arr.copy()
arr_view = arr.view()

print(arr_copy.base)  # Output: None (independent copy)
print(arr_view.base)  # Output: Original array (shares data)


None
[1 2 3 4 5]


- If base is None, it means the array owns its data (i.e., it's a copy).

- If base is not None, it means the array is a view (i.e., it shares data).

In [4]:
array1 = np.array([1,2,3,4,5,6,7])
x = array1.view()
array1[0] = 42
print(array1)
print(x)
#Here view doesnt create a new array of data for them, they do the changes in the old array itself 

[42  2  3  4  5  6  7]
[42  2  3  4  5  6  7]


In [5]:
array2 = np.array([1,2,3,4,5,6,7])
x = array2.view()
x[2] = 31
print(array2)
print(x)


[ 1  2 31  4  5  6  7]
[ 1  2 31  4  5  6  7]


In [6]:
# The original array SHOULD be affected by the changes made to the view.

# id() Function in View

- Checks if two arrays have the same memory location.

In [7]:
print(id(arr))        # Memory address of original array
print(id(arr_view))   # Memory address of view (same)


2467869191664
2467613408016


- arr_view has the same memory address as arr, confirming it's a view.
