In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4,5]

In [3]:
lst

[1, 2, 3, 4, 5]

In [4]:
print("1-D Array")
a=np.array([1,2,3,4,5])
print(a)

print("2-D Array")
b=np.array([[1,2,3,4,5],
          [6,7,8,9,10]])
print(b)

print("3-D Array")
c=np.array([[[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15]]])
print(c)

1-D Array
[1 2 3 4 5]
2-D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3-D Array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [5]:
type(c)

numpy.ndarray

In [6]:
#Size->Return the number of elements in that array
print(a.size)
print(b.size)
print(c.size)

5
10
15


In [7]:
#shape->Return the shape of an array[shape=(row,col)]
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [8]:
#dtype->Type of data present in the array
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
int32


In [9]:
#transpose->Returns an array with axes transposed[row becomes column and column becomes row]
b.transpose()

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [10]:
#empty->Return a new array of given shape and type, without initializing entries
np.empty((2,2),dtype=int)

array([[ 133318840, 1972814204],
       [-588934769, 1423571141]])

In [11]:
#np.ones((row,col),dtype)
x=np.ones(4)
x

array([1., 1., 1., 1.])

In [12]:
y=np.ones((2,3))
y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
z=np.ones((2,3),dtype=int)
z

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
#np.zeros((row,col),dtype)
x=np.zeros(4)
x

array([0., 0., 0., 0.])

In [15]:
y=np.zeros((2,3))
y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
z=np.zeros((2,3),dtype=int)
z

array([[0, 0, 0],
       [0, 0, 0]])

In [17]:
z=np.ones((2,3),dtype=str)
z

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [18]:
z=np.zeros((2,3),dtype=str)
z

array([['', '', ''],
       ['', '', '']], dtype='<U1')

In [19]:
z=np.ones((2,3),dtype=bool)
z

array([[ True,  True,  True],
       [ True,  True,  True]])

In [20]:
z=np.zeros((2,3),dtype=bool)
z

array([[False, False, False],
       [False, False, False]])

In [21]:
#np.arange(start,stop,step)->Return evenly spaced values within a given interval
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
b=np.arange(9)
b=b.reshape((3,3))

In [24]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
#flatten->Return a copy of the array collapsed into one dimension
b=b.flatten()

In [26]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
#ravel->Return a flattened array
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a=np.arange(1,51)

In [31]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [32]:
a=a.reshape(10,5)

In [33]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [34]:
a[4]

array([21, 22, 23, 24, 25])

In [35]:
a[0,0]

1

In [36]:
a[0][0]

1

In [37]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [38]:
a[0:4,2]

array([ 3,  8, 13, 18])

In [39]:
a[0:4,2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])

In [40]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

In [41]:
x,y

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [42]:
np.add(x,y) #or x+y

array([[ 6,  8],
       [10, 12]])

In [43]:
np.subtract(x,y) #or x-y

array([[-4, -4],
       [-4, -4]])

In [44]:
np.multiply(x,y) #this is not matrix multiplication it is linear multiplication

array([[ 5, 12],
       [21, 32]])

In [45]:
np.matmul(x,y) #this is matrix multiplication

array([[19, 22],
       [43, 50]])

In [46]:
x@y #this is also doing matrix multiplication

array([[19, 22],
       [43, 50]])

In [47]:
np.divide(x,y) #or x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [48]:
np.sqrt(x) #will give square root of matrix x

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [49]:
np.dot(x,y) #Dot product of two arrays

array([[19, 22],
       [43, 50]])

In [50]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [51]:
x,y

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [52]:
np.min(x) #or x.min()

1

In [53]:
np.max(x) #or x.max()

4

In [54]:
np.argmax(x)

3

In [55]:
np.sum(x)

10

In [56]:
np.sum(x,axis=0)

array([4, 6])

In [57]:
np.sum(x,axis=1)

array([3, 7])

In [58]:
np.std(x)

1.118033988749895

In [59]:
np.mean(x)

2.5

In [60]:
np.log(x)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [61]:
#np.random.random->Return random floats in the half-open interval [0.0, 1.0)
print(np.random.random())
print()
print(np.random.random(2),"->1-D")
print()
print(np.random.random((2,2)),"->2-D")

0.6737122617688377

[0.50494898 0.14925478] ->1-D

[[0.20054416 0.21816452]
 [0.62710756 0.46842863]] ->2-D


In [62]:
#Return random integers from `low` (inclusive) to `high` (exclusive)
print(np.random.randint(1,10))
print()
print(np.random.randint(1,10,3))
print()
print(np.random.randint(1,10,(2,2)))
print()
print(np.random.randint(1,10,(2,4,3)))

3

[1 8 4]

[[1 5]
 [7 6]]

[[[9 3 6]
  [2 6 7]
  [2 9 3]
  [8 7 9]]

 [[5 7 2]
  [7 7 3]
  [8 7 1]
  [1 5 2]]]


In [63]:
#Random values in a given shape
np.random.rand(2,2)

array([[0.41126409, 0.40865961],
       [0.37446199, 0.01379351]])

In [64]:
np.random.randn(2,2)

array([[0.43710828, 0.27398304],
       [0.54641358, 1.39184893]])

In [65]:
a=np.arange(10)

In [66]:
np.random.choice(a)

3

In [67]:
s1="Abhishek Dhawan"
s2="Kaise ho aap"

In [68]:
#Return element-wise string concatenation for two arrays of str or unicode
np.char.add(s1,s2)

array('Abhishek DhawanKaise ho aap', dtype='<U27')

In [69]:
#Return an array with the elements converted to uppercase
np.char.upper(s2)

array('KAISE HO AAP', dtype='<U12')

In [70]:
#Return an array with the elements converted to lowercase
np.char.lower(s1)

array('abhishek dhawan', dtype='<U15')

In [71]:
#or each element in `a`, return a list of the words in the string, using `sep` as the delimiter string
np.char.split(s2)

array(list(['Kaise', 'ho', 'aap']), dtype=object)

In [72]:
s3="Abhishek is my\nname"
#For each element in `a`, return a list of the lines in the element, breaking at line boundaries
np.char.splitlines(s3)

array(list(['Abhishek is my', 'name']), dtype=object)

In [73]:
np.char.replace(s1,"Dhawan","is my name")

array('Abhishek is my name', dtype='<U19')

In [74]:
a=[]

In [75]:
for i in range(5):
    a.append(i)

In [76]:
a

[0, 1, 2, 3, 4]

In [77]:
type(a)

list

we will convert a into array as all the calculations takes place on array

In [78]:
a=np.array(a)

In [79]:
a

array([0, 1, 2, 3, 4])

In [80]:
a.ndim

1

In [81]:
type(a)

numpy.ndarray

In [82]:
b=np.array([[1,2,3],[2,3,4]])

In [83]:
b

array([[1, 2, 3],
       [2, 3, 4]])

In [84]:
b.ndim

2

In [85]:
b[0,1:]

array([2, 3])

In [86]:
b[1,::2]

array([2, 4])

In [87]:
b[1]

array([2, 3, 4])

In [88]:
b[1][1]

3

In [89]:
b.shape #will give dimensions of array

(2, 3)

In [90]:
len(b)

2

In [91]:
len(b[0])

3

In [92]:
c=np.full((3,2),10)

In [93]:
c

array([[10, 10],
       [10, 10],
       [10, 10]])

Identity matrix-diagoanl elements are 1 and rest elements are 0

In [94]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [95]:
np.eye(4,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [96]:
np.random.random()

0.9822943397746865

In [97]:
d=np.random.random((5,5))

In [98]:
d

array([[0.38872634, 0.35768118, 0.81178411, 0.75555805, 0.05891612],
       [0.30721772, 0.49169388, 0.01793182, 0.29716344, 0.65996007],
       [0.09391611, 0.13305592, 0.19866786, 0.90904738, 0.58030788],
       [0.9578959 , 0.53154965, 0.13646442, 0.41787512, 0.18251573],
       [0.7984129 , 0.97326114, 0.74964104, 0.62057318, 0.70297274]])

In [99]:
ran=d[0]

In [100]:
ran

array([0.38872634, 0.35768118, 0.81178411, 0.75555805, 0.05891612])

In [101]:
d[:2,3:]

array([[0.75555805, 0.05891612],
       [0.29716344, 0.65996007]])

In [102]:
p=np.random.randint(10,20,3) #an array of 3 elemets from 10 to 20 will be provided

In [103]:
p

array([18, 16, 19])

In [104]:
q=np.random.randint(10,20,(3,3))

In [105]:
q

array([[17, 18, 17],
       [14, 18, 17],
       [16, 12, 10]])

In [106]:
choice=np.random.choice(p) #Generates a random sample from a given 1-D array

In [107]:
choice

19

In [108]:
np.random.rand(2) #create array of 2 elements and elements will be random number between 0 to 1

array([0.03597013, 0.82545044])

In [109]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

In [110]:
x,y

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [111]:
np.add(x,y) #or x+y

array([[ 6,  8],
       [10, 12]])

In [112]:
np.subtract(x,y) #or x-y

array([[-4, -4],
       [-4, -4]])

In [113]:
np.multiply(x,y) #this is not matrix multiplication it is linear multiplication

array([[ 5, 12],
       [21, 32]])

In [114]:
np.matmul(x,y) #this is matrix multiplication

array([[19, 22],
       [43, 50]])

In [115]:
x@y #this is also doing matrix multiplication

array([[19, 22],
       [43, 50]])

In [116]:
np.divide(x,y) #or x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [117]:
np.sqrt(x) #will give square root of matrix x

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [118]:
np.dot(x,y) #Dot product of two arrays

array([[19, 22],
       [43, 50]])

In [119]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [120]:
arr=np.array([[1,2,3],[4,5,6]])

In [121]:
flattened=arr.flatten()

In [122]:
flattened  #creates a new memory location for flattened variable

array([1, 2, 3, 4, 5, 6])

In [123]:
ravelled=arr.ravel()

In [124]:
ravelled  #changes the original array

array([1, 2, 3, 4, 5, 6])

In [125]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])

In [126]:
b=b**2

In [127]:
b

array([ 1,  4,  9, 16, 25])

In [128]:
np.stack((a,b),axis=0),np.stack((a,b),axis=0).shape #axis=0 means in form of row

(array([[ 1,  2,  3,  4,  5],
        [ 1,  4,  9, 16, 25]]),
 (2, 5))

In [129]:
np.stack((a,b),axis=1),np.stack((a,b),axis=1).shape #axis=1 means in form of column

(array([[ 1,  1],
        [ 2,  4],
        [ 3,  9],
        [ 4, 16],
        [ 5, 25]]),
 (5, 2))

In [130]:
a=np.stack((a,b),axis=0)

In [131]:
a,a.shape

(array([[ 1,  2,  3,  4,  5],
        [ 1,  4,  9, 16, 25]]),
 (2, 5))

In [132]:
a.reshape(1,10)

array([[ 1,  2,  3,  4,  5,  1,  4,  9, 16, 25]])

In [133]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  1],
       [ 4,  9],
       [16, 25]])

In [134]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [135]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [136]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [137]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [138]:
a=a.flatten()

In [139]:
a

array([ 1,  2,  3,  4,  5,  1,  4,  9, 16, 25])

In [140]:
np.min(a)

1

In [141]:
np.max(a)

25

In [142]:
np.average(a)

7.0

In [143]:
np.mean(a)

7.0

In [144]:
np.std(a)

7.37563556583431

In [145]:
b=np.array([[1,2,3],[2,3,4]])

In [146]:
np.expand_dims(b,axis=0)  # np.expand_dims(b,axis=0) -> [x,y]

array([[[1, 2, 3],
        [2, 3, 4]]])

In [147]:
np.expand_dims(b,axis=1) # np.expand_dims(b,axis=0) -> [[x],[y]]

array([[[1, 2, 3]],

       [[2, 3, 4]]])

In [148]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])

In [149]:
a,b    

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [150]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [151]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])