# Splitting the NumPy Array

- Splitting NumPy Arrays refers to the process of dividing a large NumPy array into multiple smaller arrays based on specified conditions or indices.

- This is particularly useful when you have a large dataset, and you need to break it down into smaller segments for analysis, processing, or manipulation.

- Splitting can be done horizontally (column-wise), vertically (row-wise), or depth-wise (for 3D arrays).

# Methods Associated with Splitting NumPy Arrays 

# 1) np.split() Method (Equal Split)

- Splits the array into equal parts.

- If the array cannot be split equally, it will raise an error.

In [1]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9])
split_array = np.split(array, 3)
print(split_array)


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


# 2) np.array_split() Method (Unequal Split)

- Splits the array into unequal parts.

- Does not raise an error if the array size is not divisible.

In [2]:
split_array = np.array_split(array, 4)
print(split_array)


[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


# 3) np.hsplit() Method (Horizontal Split)

- Splits the array column-wise.

In [3]:
array = np.array([[1,2,3],[4,5,6]])
split_array = np.hsplit(array, 3)
print(split_array)


[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


# 4) np.vsplit() Method (Vertical Split)

- Splits the array row-wise.

In [4]:
split_array = np.vsplit(array, 2)
print(split_array)


[array([[1, 2, 3]]), array([[4, 5, 6]])]


# Features of Splitting NumPy Arrays

# 1) Can Split Along Any Axis

-  Can Split Along Any Axis

- It is mainly used when you have a large array and you need to break it into smaller arrays for processing.

# 2) Maintains Data Structure

- Splitting an array does not change the structure of individual smaller arrays.

- They still remain NumPy arrays and can be further manipulated.

# 3) Handles Multi-Dimensional Arrays

- It supports 1D, 2D, and 3D arrays.

- You can even split along depth for 3D arrays.

# 4) Different Splitting Methods

- split() → For equal splitting.

- array_split() → For unequal splitting.

- vsplit() → Split along rows.

- hsplit() → Split along columns.

- dsplit() → Split along depth.

# 1) split() Method → For Equal Splitting

- The split() method in NumPy is used to split an array into equal parts (sub-arrays) along a specified axis.

- This method is useful when you have an array and you want to divide it into equal parts based on the size.

- The array is split into equal parts only.

- It can split the array along any axis (rows, columns, or depth).

- numpy.split(array, sections, axis=0) -------> Syntax

- array → The input NumPy array to be split.

- sections → The number of equal parts the array should be divided into.

- axis → The axis along which the split is to be performed

- axis=0 → Split along rows (default).

- axis=1 → Split along columns.

- axis=2 → Split along depth (for 3D arrays).



In [5]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6])

# Splitting the array into 3 equal parts
result = np.split(arr, 3)

# Printing the result
for i, sub_array in enumerate(result):
    print(f"Sub-array {i+1}: {sub_array}")


Sub-array 1: [1 2]
Sub-array 2: [3 4]
Sub-array 3: [5 6]


# 2) array_split() Method → For Unequal Splitting

- The array_split() method is used to split an array into unequal parts.

- It is more flexible than split().

- It can split the array into unequal parts.

- If the array size is not divisible equally, the last sub-array may have fewer elements.

- numpy.array_split(array, sections, axis=0) ------> Syntax


In [6]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Splitting the array into 3 unequal parts
result = np.array_split(arr, 3)

# Printing the result
for i, sub_array in enumerate(result):
    print(f"Sub-array {i+1}: {sub_array}")


Sub-array 1: [1 2 3]
Sub-array 2: [4 5]
Sub-array 3: [6 7]


# 3) vsplit() Method → Split Along Rows (Vertical Splitting)

- The vsplit() method is used to split an array along rows (vertically).

- It is equivalent to using split() with axis=0.

- It always splits vertically along rows.

- It is mostly used for 2D arrays (matrices).

- numpy.vsplit(array, sections) ----> Syntax

In [7]:
import numpy as np

# Creating a 2D NumPy array
arr = np.array([[1, 2],
                [3, 4],
                [5, 6],
                [7, 8]])

# Splitting the array into 2 equal parts vertically
result = np.vsplit(arr, 2)

# Printing the result
for i, sub_array in enumerate(result):
    print(f"Sub-array {i+1}:\n{sub_array}")


Sub-array 1:
[[1 2]
 [3 4]]
Sub-array 2:
[[5 6]
 [7 8]]


# 4) hsplit() Method → Split Along Columns (Horizontal Splitting)

- The hsplit() method is used to split an array along columns (horizontally).

- It splits the array along columns.

- It works only for 2D or higher arrays.

- numpy.hsplit(array, sections) #Syntax


In [8]:
import numpy as np

# Creating a 2D NumPy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

# Splitting the array into 2 equal parts horizontally
result = np.hsplit(arr, 2)

# Printing the result
for i, sub_array in enumerate(result):
    print(f"Sub-array {i+1}:\n{sub_array}")


Sub-array 1:
[[1 2]
 [5 6]]
Sub-array 2:
[[3 4]
 [7 8]]
