In [1]:
import numpy as np
narray = np.array([1,2,3,4,5,6,7])
print(narray[1:5:1])#Acessing the 2nd Element to 4th Element with indexing as step as 1.


[2 3 4 5]


In [2]:
#Slice elements from index 4 to the end of the array
print(narray[4:])

[5 6 7]


In [3]:
#Slice elements from the beginning to index 4 (not included)
narray = np.array([1,2,3,4,5,6,7])
print(narray[:4])


[1 2 3 4]


In [4]:
#Return every other(alternate) element from index 1 to index 5
narray = np.array([1,2,3,4,5,6,7])
print(narray[1:5:2])


[2 4]


In [5]:
#step value above is adding the condition, like we had to print numbers from index no. 2 to 5.
#Return every other element from the entire array


In [6]:
narray = np.array([1,2,3,4,5,6,7])
print(narray[::2])


[1 3 5 7]


In [7]:
#2-d array-From the second element, slice elements from index 1 to index 4 (not included)
narray = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(narray[1, 1:4])


[7 8 9]


In [8]:
#In the above example, we have been told from the 2nd element which means the 2nd array jiski indexing ha 1(0,1), now in the 2nd element slice elements from index 1 to 4
#From both elements, return index 2
narray = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(narray[0:2, 3])



[4 9]


In [9]:
#In the above example as we are having 2-d array and we need to return index 2 from both so pehle arrays likhenge(0:2) now 0:2 means array at 0th position which is [1,2,3,4,5] and array at 2th means 1st position pe(because 2 se pehle vala no. lete ha na)1st which is [6,7,8,9,10] and then comma daalkar jaha se indexing chahiye dono mein voh add krdo.
