# Data - Types in NumPy Array

- In NumPy Arrays, data types (dtype) represent the type of data stored in an array.

- Every element in a NumPy array has a specific data type such as:

- Integers (int32, int64)

- Floating Point Numbers (float32, float64)

- Boolean (bool)

- Complex Numbers (complex64, complex128)

- Strings

In [1]:
import numpy as np
narray = np.array([1,2,3,4])
print(narray.dtype)


int32


In [2]:
#dtype property tells u which data type of your NumPy Array
array1 = np.array(['apple', 'banana', 'cherry'])
print(array1.dtype)


<U6


In [3]:
#Creating Arrays With a Defined Data Type
narray = np.array([1,2,3,4], dtype= 'S')
print(narray)
print(narray.dtype)

[b'1' b'2' b'3' b'4']
|S1


# Different Data Types in NumPy Array

In [4]:
#Importing the NumPy library
import numpy as np

#Integer Data Type Array (int32)
int_array = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print("Integer Array:")
print(int_array)
print("Data Type:", int_array.dtype)


#Float Data Type Array (float64)
float_array = np.array([1.1, 2.2, 3.3, 4.4], dtype=np.float64)
print("Float Array:")
print(float_array)
print("Data Type:", float_array.dtype)


#Boolean Data Type Array (bool)
bool_array = np.array([True, False, True, False], dtype=np.bool_)
print("Boolean Array:")
print(bool_array)
print("Data Type:", bool_array.dtype)


#Complex Number Data Type Array (complex64)
complex_array = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex64)
print("Complex Number Array:")
print(complex_array)
print("Data Type:", complex_array.dtype)


#String Data Type Array (str)
string_array = np.array(['apple', 'banana', 'cherry'], dtype=np.str_)
print("String Array:")
print(string_array)
print("Data Type:", string_array.dtype)


#Object Data Type Array (object)
object_array = np.array([1, 'apple', 3.5, True], dtype=np.object_)
print("Object Array:")
print(object_array)
print("Data Type:", object_array.dtype)



Integer Array:
[1 2 3 4 5]
Data Type: int32
Float Array:
[1.1 2.2 3.3 4.4]
Data Type: float64
Boolean Array:
[ True False  True False]
Data Type: bool
Complex Number Array:
[1.+2.j 3.+4.j 5.+6.j]
Data Type: complex64
String Array:
['apple' 'banana' 'cherry']
Data Type: <U6
Object Array:
[1 'apple' 3.5 True]
Data Type: object


# Features of Data Types in NumPy Array

# 1) Homogeneous Data i.e. Same Data Type


- In a NumPy Array, all elements must have the same data type i.e. Homogeneous Data.

- This ensures faster processing and memory efficiency.

In [5]:
#Importing the NumPy Library
import numpy as np

#Creating an Integer Array
int_array = np.array([10, 20, 30, 40], dtype=np.int32)
print("Integer Array:")
print(int_array)
print("Data Type:", int_array.dtype)


#Creating a Float Array
float_array = np.array([1.5, 2.5, 3.5, 4.5], dtype=np.float64)
print("Float Array:")
print(float_array)
print("Data Type:", float_array.dtype)


Integer Array:
[10 20 30 40]
Data Type: int32
Float Array:
[1.5 2.5 3.5 4.5]
Data Type: float64


# 2) Fixed Size of Data Types i.e Fixed Byte Size

- Every element in a NumPy array consumes a fixed size of memory.


In [6]:
#Importing NumPy Library
import numpy as np

#Creating an Integer Array
arr = np.array([10, 20, 30, 40], dtype=np.int32)

#Checking the size of each element in bytes
print("Array Elements:", arr)
print("Data Type of Array:", arr.dtype)
print("Size of Each Element (in bytes):", arr.itemsize)
print("Total Memory Consumed (in bytes):", arr.nbytes)


Array Elements: [10 20 30 40]
Data Type of Array: int32
Size of Each Element (in bytes): 4
Total Memory Consumed (in bytes): 16


# 3) Faster Processing and Computation

- NumPy Arrays are highly optimized for fast mathematical computations.

In [7]:
import numpy as np
import time

#Creating a NumPy Array of 1 Million Elements
arr = np.array(range(1000000), dtype=np.int32)

#Measuring the Time Taken to Add 5 to Each Element
start_time = time.time()
arr += 5
end_time = time.time()

print("Time Taken for Addition:", end_time - start_time)


Time Taken for Addition: 0.011967897415161133


# 4) Data Type Conversion i.e. Type Casting

- NumPy allows you to change the data type (Type Casting) using the astype() method.


- This is very useful when converting:

- Integer → Float

- Boolean → Integer

- String → Integer

In [8]:
#Importing NumPy Library
import numpy as np

#Creating an Integer Array
arr = np.array([10, 20, 30, 40], dtype=np.int32)

#Converting Integer to Float
float_arr = arr.astype(np.float64)
print("Float Array:")
print(float_arr)
print("Data Type:", float_arr.dtype)

#Converting Integer to Boolean
bool_arr = arr.astype(np.bool_)
print("Boolean Array:")
print(bool_arr)
print("Data Type:", bool_arr.dtype)


Float Array:
[10. 20. 30. 40.]
Data Type: float64
Boolean Array:
[ True  True  True  True]
Data Type: bool


# Attributes Associated with Data Types in NumPy Arrays

In [9]:
#Import NumPy
import numpy as np

#Create an NumPy Array
arr = np.array([10, 20, 30, 40, 50], dtype=np.int32)

#Check Data Type of Array
print("Data Type:", arr.dtype)

#Check Size of Array
print("Number of Elements:", arr.size)

#Check Size of Each Element (in bytes)
print("Size of Each Element:", arr.itemsize)

#Check Total Number of Bytes Consumed
print("Total Bytes Consumed:", arr.nbytes)


Data Type: int32
Number of Elements: 5
Size of Each Element: 4
Total Bytes Consumed: 20


# Methods Associated with Data Types in NumPy Arrays

In [10]:
#Import NumPy
import numpy as np

#Create Integer NumPy Array
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)

#Convert Integer to Float
float_arr = arr.astype(np.float64)
print("Float Array:", float_arr)

#Fill the NumPy Array with Value 100
arr.fill(100)
print("Filled Array:", arr)


Float Array: [1. 2. 3. 4. 5.]
Filled Array: [100 100 100 100 100]
