In [35]:
import numpy as np #Importing the NumPy Library.

# Creating Array From List

In [36]:
arr_1d = np.array([1,2, 3, 4,5])
print("1-D Array", arr_1d)

1-D Array [1 2 3 4 5]


In [37]:
arr_2d = np.array([[1,2,3], [4, 5,6]])
print("2-D Array", arr_2d)

2-D Array [[1 2 3]
 [4 5 6]]


# List vs NumPy Array

In [38]:
py_list = [1,2,3]
print(" Python List Multiplication", py_list * 2 )

 Python List Multiplication [1, 2, 3, 1, 2, 3]


In [39]:
np_array = np.array([1,2,3])#element - wise multiplication
print("Python array multiplication", np_array *2)

Python array multiplication [2 4 6]


In [40]:
zeros = np.zeros((3, 4))#creating array from zeros
print("zeros array:\n", zeros)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [41]:
ones = np.ones((2,3))#creating array from ones
print("one array\n", ones)

one array
 [[1. 1. 1.]
 [1. 1. 1.]]


In [42]:
full = np.full((2, 2), 7)
print("full array:\n", full)

full array:
 [[7 7]
 [7 7]]


In [43]:
random = np.random.random((2, 3))
print("random array:\n", random)

random array:
 [[0.8581067  0.16499192 0.32608664]
 [0.44231431 0.58154596 0.49667026]]


In [44]:
sequence = np.arange(0, 10,2)
print("sequence array:\n", sequence)

sequence array:
 [0 2 4 6 8]


# Vectors, Matrix and Tensor

In [45]:
vector = np.array([1,2,3])
print("Vectors", vector)

Vectors [1 2 3]


In [46]:
matrix = np.array([[1,2,3], 
                  [4,5,6]])
print("Matrix:", matrix)

Matrix: [[1 2 3]
 [4 5 6]]


In [47]:
tensor = np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
print("Tensors:", tensor)

Tensors: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# NumPy Array - Properties(Attributes)

In [48]:
arr = np.array([[1,2,3],
               [4,5,6]])
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("DType:", arr.dtype)

Shape: (2, 3)
Dimension: 2
Size: 6
DType: int32


# Numpy Array - Reshaping

In [49]:
arr = np.arange(12)
print("Original Array:", arr)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [50]:
reshaped = arr.reshape((3,4))
print("\n Reshaped Array", reshaped)


 Reshaped Array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [51]:
flattened = reshaped. flatten()
print("\n Flattened Array", flattened)


 Flattened Array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [52]:
raveled = reshaped.ravel()
print("\n raveled array", raveled)


 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [53]:
transpose = reshaped.T
print("\n transporsed array", transpose)



 transporsed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# Slicing in Numpy Array

In [54]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing", arr[2:7])
print("With step", arr[1:8:2])
print("negative indexing", arr[-1:-6:-1])

Basic Slicing [3 4 5 6 7]
With step [2 4 6 8]
negative indexing [10  9  8  7  6]


In [55]:
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print("Specific Element", arr_2d[1,2])
print("Entire Row", arr_2d[1])
print("Entire Row", arr_2d[:, 1])

Specific Element 6
Entire Row [4 5 6]
Entire Row [2 5 8]


# Sorting In Numpy Array

In [56]:
unsorted = np.array([10,9,8,7,6,5])
print("Sorted Array", np.sort(unsorted))

Sorted Array [ 5  6  7  8  9 10]


In [57]:
arr_2d_unsorted = np.array([[3,1], [1,2], [2,3]])
print("Sorted 2D Array by Column", np.sort(arr_2d_unsorted))

Sorted 2D Array by Column [[1 3]
 [1 2]
 [2 3]]


# Filtering in NumPy Array

In [58]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even Numbers",even_number)

Even Numbers [ 2  4  6  8 10]


# Filter With Mask

In [59]:
mask = numbers > 5
print("Numbers Greater Than 5", numbers[mask])

Numbers Greater Than 5 [ 6  7  8  9 10]


# Fancy Indexing VS np.where()

In [60]:
indices = [0,2,4]
print(numbers[indices])
where_result = np.where(numbers > 5)
print("NP where", numbers[where_result])

[1 3 5]
NP where [ 6  7  8  9 10]


In [61]:
condition_array = np.where(numbers > 5, "true", "false")
print(condition_array)


['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


# Adding and Removing the Data in NumPy Array

In [62]:
arr1 = np.array([1,2,3])
arr2= np.array((1,2,3))
arr3 = arr1 + arr2
print(arr3)

[2 4 6]


# Compatiblity of NumPy Array
- Basically, compatibility checks whether the shape of 2 or more arrays are same/ equal or not and results in true or False based on the Compatibility i.e. checking of shapes of 2 or more arrays.

In [63]:
a = np.array([1,2,3])
b = np.array([7,8,9])
print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes True


In [64]:
b = np.array([7,8,9])
c = np.array([10,11,12,13])
print("Compatibility shapes", b.shape == c.shape)

Compatibility shapes False


# vstack() - Adds a new Row in the NumPy Array


# hstack() - Adds a New Column in the NumPy Array

In [65]:
import numpy as np

original = np.array([[1,2], [3.4, 4.5]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))

print(original)
print(with_new_row)

[[1.  2. ]
 [3.4 4.5]]
[[1.  2. ]
 [3.4 4.5]
 [5.  6. ]]


In [66]:
new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With the new column",with_new_col)

With the new column [[1.  2.  7. ]
 [3.4 4.5 8. ]]


In [67]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
print("After the deletion of numpy array element",deleted)

After the deletion of numpy array element [1 2 4 5]


# Advance operation of NumPy Array - with Business Examples 

# Data Structure:[restaurant_id, 2021, 2022, 2023, 2024]

In [68]:
import matplotlib.pyplot as plt

In [69]:
sales_data = np.array([
    [1, 15000, 18000, 22000, 25000],#Paradise Biryani
    [2, 12000, 14000, 16000, 19000],#Beijing Bites
    [3, 20000, 23000, 26000, 30000],#Pizza Hub
    [4, 18000, 21000, 240000,27000],#Burger Point
    [5, 16000, 18500, 20500, 23000]#Chai Point
    ])
print("Zomato Data Analysis")
print("\nSales Data Shape:", sales_data.shape)
print("\nSample Data for 1st 3 Restraunts:",sales_data[3])

Zomato Data Analysis

Sales Data Shape: (5, 5)

Sample Data for 1st 3 Restraunts: [     4  18000  21000 240000  27000]


In [70]:
#Total Sales Per Year
print(np.sum(sales_data, axis = 0))#Column - Wise Total

[    15  81000  94500 324500 124000]


In [71]:
yearly_total = np.sum(sales_data[1:5:1], axis = 1)#Row - Wise Total
print(yearly_total)

[ 61002  99003 306004  78005]


In [72]:
#Minimum Sales of each Restraunt
min_sales = np.min(sales_data, axis = 1)
print(min_sales)

[1 2 3 4 5]


In [73]:
#Maximum Sales per Restraunt


In [74]:
#Average Sales per Restraunt

In [75]:
#Cummlative Sales Per Restraunt

In [76]:
plt.figure()

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>