# Shape of NumPy Array
1) In NumPy, the shape of an array represents the dimensions of the array in the form of a tuple. It tells us how many elements are present along each axis.

2) The shape attribute of a NumPy array returns a tuple where:

- The first value represents the number of rows.

- The second value represents the number of columns(for 2D arrays).

- Additional values represent dimensions in higher-dimensional arrays.



In [1]:
import numpy as np
narray = np.array([[1,2,3,4,5],[6,7,8,9,10]])#Printing the shape of the NumPy 2-D Array
print(narray.shape)#The above example above will return (2, 5), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 5.


(2, 5)


In [2]:
import numpy as np

# Creating a 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Checking shape of the array
print("Shape of the array:", arr.shape)


Shape of the array: (2, 3)


In [3]:
#The shape (2, 3) means the array has 2 rows and 3 columns.


In [4]:
array_np = np.array([1,2,3,4,9,10], ndmin=5)
print(array_np)
print('shape of the array is:',array_np.shape)


[[[[[ 1  2  3  4  9 10]]]]]
shape of the array is: (1, 1, 1, 1, 6)


In [5]:
#Features of Shape in NumPy Array.
#1)The shape is always in the form of a tuple.
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)  # Output: (5,)


(5,)


In [6]:
#The shape (5,) means the array has 1 dimension with 5 elements.

In [7]:
#2)Shape Changes Dynamically:The shape of an array can be changed using reshape() or directly modifying the .shape attribute.
arr = np.array([1, 2, 3, 4, 5, 6])
arr = arr.reshape(2, 3)
print(arr.shape)  # Output: (2, 3)


(2, 3)


In [8]:
#Reshaping changes the dimensions without modifying the data.

In [9]:
#3)Also works with Higher-Dimensional NumPy Arrays
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr.shape)  # Output: (2, 2, 2)



(2, 2, 2)


In [10]:
#(2, 2, 2) means:
#1)2 blocks (depth)
#2)2 rows
#3)2 columns

# .reshape() Method in NumPy Array

- The .reshape() method in NumPy is used to change the shape (dimension) of an existing NumPy array without changing its data.

- It means you can transform a 1-D array into 2-D, 3-D, or any higher dimensional array as long as the number of elements remains the same.



In [11]:
#Used to change the shape of NumPy Array.
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(3, 2)  #Changing to 3 rows, 2 columns
print(reshaped_arr)


[[1 2]
 [3 4]
 [5 6]]


In [12]:
#The total number of elements must remain the same before and after reshaping.


# .resize() Method in NumPy Array

- The .resize() method in NumPy is used to change the shape (dimension) and size of an existing NumPy array.

- It is very similar to the .reshape() method but has some major differences, which we will cover later.

- The .resize() method allows you to increase or decrease the size of an array.

- If the new shape has more elements than the original, it fills the remaining elements with 0 or garbage values.

- If the new shape has fewer elements than the original, it truncates (removes) the excess elements.

In [13]:
#It is similar to reshape(), but modifies the array in place.
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize(2, 3)
print(arr.shape)  # Output: (2, 3)


(2, 3)


# .ndim Attribute in NumPy Array

- The .ndim attribute in NumPy is used to get the number of dimensions (axes) of a NumPy array.

- 1D Array: Single line of elements (like a list in Python).

- 2D Array: Rows and Columns (like a matrix or table).

- 3D Array: Multiple 2D arrays stacked (like a cube or multiple layers).

- The .ndim attribute simply tells us how many dimensions the array has.



In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)  # Output: 2 (2D array)


2


# Checking the Shape of Different NumPy Arrays

In [15]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr1.shape)  # Output: (5,)
print(arr2.shape)  # Output: (2, 3)
print(arr3.shape)  # Output: (2, 2, 2)


(5,)
(2, 3)
(2, 2, 2)


# Reshaping NumPy Arrays

- Reshaping in NumPy means changing the structure or shape (dimensions) of an existing NumPy array without changing its data.

- We can convert a 1-D Array to a 2-D Array.

- We can convert a 1-D array to a 3-D array.

- We can convert a 2-D array to a 3-D array

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping to 2 rows and 3 columns
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

# Reshaping to 3 rows and 2 columns
reshaped_arr = arr.reshape(3, 2)
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


# Flattening NumPy Arrays

- Converts an array into a 1D array.

- Flattening an array in NumPy means converting a multi-dimensional array (2D, 3D, 4D, etc.) into a 1-dimensional array (1D).

- Convert 2D → 1D 

- 3D → 1D

-  4D → 1D

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flat_arr = arr.reshape(-1)
print(flat_arr)  # Output: [1 2 3 4 5 6]


[1 2 3 4 5 6]
