# Numpy Basics


In [1]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [2]:
import numpy as np

print(np.__version__)


1.26.4


# Numpy creating arrays


# 1) From List

In [3]:
import numpy as np
array= numpy.array([6,7,8,9,10])#From a list - Creating Numpy Array
print(array)
print(type(array))


[ 6  7  8  9 10]
<class 'numpy.ndarray'>


# 2) From Tuple

In [4]:
#Use a tuple to create a NumPy array
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)



[1 2 3 4 5]


In [5]:
#Dimensional arrays:
#A dimension in arrays is one level of array depth (nested arrays).
#Nested array: are arrays that have arrays as their elements.

#0-D array
#0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

#Create a 0-D array with value 150
a= np.array(150)
print(a)


150


In [6]:
#Create a 1-D array using the zeros
b = np.zeros(5)
print(b)


[0. 0. 0. 0. 0.]


In [7]:
#Create a 1-D array using the ones
c = np.ones(6)
print(c)

[1. 1. 1. 1. 1. 1.]


In [8]:
#Create a 3-D array with two 2-D arrays, both containing two arrays.
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.
#These are often used to represent a 3rd order tensor.

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
#Checking the dimensions of the NumPy Array
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [10]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:
a = np.array([1, 2, 3, 4], ndmin=5)
print(a)
print('number of dimensions :', a.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
