# Mathematical Functions in NumPy

-Mathematical functions in NumPy are built-in functions that allow users to perform element-wise operations on arrays. 

-These functions operate efficiently on NumPy arrays and support vectorized operations, making them faster than traditional Python loops.



# Key Mathematical Operations:

# 1) np.sum():

- Computes the sum of  NumPy Array elements.


# 2) np.prod():

- Computes the product of all NumPy Array elements.

# 3) np.mean():

- Returns the mean (average) of all NumPy Array Elements.


# 4) np.std()

- Returns the standard deviation of all NumPy Array Elements.


In [1]:
import numpy as np  # Importing NumPy library.

# Creating a NumPy Array
arr = np.array([1, 2, 3, 4, 5])

# Basic Mathematical Operations
sum_arr = np.sum(arr)  # Sum of all elements
product_arr = np.prod(arr)  # Product of all elements
mean_arr = np.mean(arr)  # Mean (average) of elements
std_arr = np.std(arr)  # Standard deviation

# Displaying Results
print("Original Array:", arr)
print("Sum:", sum_arr)
print("Product:", product_arr)
print("Mean:", mean_arr)
print("Standard Deviation:", std_arr)


Original Array: [1 2 3 4 5]
Sum: 15
Product: 120
Mean: 3.0
Standard Deviation: 1.4142135623730951


# Features of Mathematical Functions in NumPy

- Vectorized Computation: NumPy functions apply operations on entire arrays without the need for explicit loops.



- Support for Multi-Dimensional Arrays: Functions work efficiently on multi-dimensional  NumPy Arrays.



- Broadcasting: Allows operations between arrays of different shapes.



- Performance Optimization: NumPy is implemented in C, making it significantly faster than Python loops.



- Element-wise Execution: Functions perform operations on each element independently.

# 1) np.square(): 

- Squares each element in the array.

# 2) np.sqrt(): 
    
- Computes the square root of each element.

In [2]:
import numpy as np

# Creating a 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Applying element-wise mathematical functions
squared_arr = np.square(arr)  # Squaring each element
sqrt_arr = np.sqrt(arr)  # Square root of each element

# Broadcasting Example
vector = np.array([1, 2, 3])
broadcasted_result = arr + vector  # Broadcasting addition

# Displaying Results
print("Original 2D Array:\n", arr)
print("Squared Array:\n", squared_arr)
print("Square Root Array:\n", sqrt_arr)
print("Broadcasted Addition Result:\n", broadcasted_result)


Original 2D Array:
 [[1 2 3]
 [4 5 6]]
Squared Array:
 [[ 1  4  9]
 [16 25 36]]
Square Root Array:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
Broadcasted Addition Result:
 [[2 4 6]
 [5 7 9]]


# Different Attributes Related to Mathematical Functions in NumPy

# Key Attributes:

# 1) ndim

- Number of dimensions in the NumPy Array.

## 2) shape

- Shape of the array (rows, columns).

# 3) size

- Total number of elements in the NumPy Array.

# 4) dtype

- Data type of elements in the NumPy Array.

In [3]:
import numpy as np

# Creating a NumPy array
arr = np.array([[1.5, 2.3, 3.7], [4.1, 5.6, 6.8]])

# Accessing attributes
num_dimensions = arr.ndim  # Number of dimensions
shape_of_array = arr.shape  # Shape (rows, columns)
size_of_array = arr.size  # Total elements in array
data_type = arr.dtype  # Data type of array elements

# Displaying Results
print("Array:\n", arr)
print("Number of Dimensions:", num_dimensions)
print("Shape of Array:", shape_of_array)
print("Size of Array:", size_of_array)
print("Data Type of Elements:", data_type)


Array:
 [[1.5 2.3 3.7]
 [4.1 5.6 6.8]]
Number of Dimensions: 2
Shape of Array: (2, 3)
Size of Array: 6
Data Type of Elements: float64
