# Iterating NumPy Arrays

- Iterating means accessing each element of the NumPy array one-by-one.

- In Python, we can iterate through a NumPy array using loops (like for loop) or using in-built NumPy functions.

- Iterating allows us to perform operations on each element of the array individually.

# It is helpful when we want to:


- Access each element of the array.

- Modify the element of the array.

- Perform operations on each element.

- Search or filter elements from the array.

- Apply conditions on each element.

# Different Ways to Iterate NumPy Arrays in Python:

- We can iterate through NumPy arrays using the following ways:

- Using for loop (Basic Iteration).

- Using Nested for loop (for multi-dimensional arrays).

- Using flatten() method.

- Using flat attribute.

# 1) Iterating 1-D NumPy Array using for loop:

In [1]:
import numpy as np

# Creating a 1-D NumPy Array
arr = np.array([10, 20, 30, 40, 50])

# Iterating through the 1-D Array using a for loop
print("Elements in the array are:")
for element in arr:
    print(element)


Elements in the array are:
10
20
30
40
50


# 2) Iterating 2-D NumPy Array using Nested for loop:

In [2]:
import numpy as np

# Creating a 2-D NumPy Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Iterating through the 2-D Array using Nested for loop
print("Elements in the 2-D array are:")
for row in arr:
    for element in row:
        print(element)


Elements in the 2-D array are:
1
2
3
4
5
6


# 3) Iterating using np.nditer() Function

- np.nditer() is an advanced method provided by NumPy to iterate through multi-dimensional arrays in an efficient manner.

- It automatically handles multi-dimensional arrays without requiring a nested for loop.

In [3]:
import numpy as np

# Creating a 2-D NumPy Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Iterating through 2-D Array using np.nditer()
print("Elements in the 2-D array are:")
for element in np.nditer(arr):
    print(element)


Elements in the 2-D array are:
1
2
3
4
5
6


# 4) Iterating with Index using np.ndenumerate()

- If you also want to get the index (position) of each element while iterating, you can use np.ndenumerate().

In [4]:
import numpy as np

# Creating a 2-D NumPy Array
arr = np.array([[10, 20],
                [30, 40]])

# Iterating with Index using np.ndenumerate()
print("Elements with their index:")
for index, element in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {element}")


Elements with their index:
Index: (0, 0), Value: 10
Index: (0, 1), Value: 20
Index: (1, 0), Value: 30
Index: (1, 1), Value: 40


# 5) Iterating Using flat Attribute

In [5]:
import numpy as np

# Creating a 2-D NumPy Array
arr = np.array([[10, 20],
                [30, 40]])

# Iterating using flat attribute
print("Elements using flat attribute:")
for element in arr.flat:
    print(element)


Elements using flat attribute:
10
20
30
40


# Features of Iterating NumPy Arrays

# 1) Fast and Efficient Iteration Using np.nditer()

In [6]:
import numpy as np

# Creating a 2-D NumPy Array
arr = np.array([[10, 20],
                [30, 40]])

# Iterating using np.nditer() for fast access
print("Elements in the array are:")
for element in np.nditer(arr):
    print(element)


Elements in the array are:
10
20
30
40


# 2) Iterate with Index Using np.ndenumerate()

In [7]:
import numpy as np

# Creating a 2-D NumPy Array
arr = np.array([[5, 10],
                [15, 20]])

# Iterating with index
print("Index and Value of each element:")
for index, value in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {value}")


Index and Value of each element:
Index: (0, 0), Value: 5
Index: (0, 1), Value: 10
Index: (1, 0), Value: 15
Index: (1, 1), Value: 20


# Attributes of Iterating NumPy Arrays

# 1) ndim Attribute - Number of Dimensions in Array

In [8]:
import numpy as np

# Creating a 1-D Array
arr = np.array([10, 20, 30])

# Creating a 2-D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Creating a 3-D Array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Printing Dimensions of Each Array
print("Number of dimensions in arr:", arr.ndim)
print("Number of dimensions in arr2:", arr2.ndim)
print("Number of dimensions in arr3:", arr3.ndim)


Number of dimensions in arr: 1
Number of dimensions in arr2: 2
Number of dimensions in arr3: 3


# 2) size Attribute - Total Number of Elements in Array

- The size attribute returns the total number of elements present in the NumPy array.

In [9]:
import numpy as np

# Creating a 2-D Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Finding the size of array
print("Total number of elements in array:", arr.size)


Total number of elements in array: 6


# 3) shape Attribute - Shape of the Array

In [10]:
import numpy as np

# Creating a 2-D Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Finding the shape of array
print("Shape of the array:", arr.shape)


Shape of the array: (2, 3)


# 4) flat Attribute - Flattening the Array

In [11]:
import numpy as np

# Creating a 2-D Array
arr = np.array([[10, 20],
                [30, 40]])

# Iterating using flat attribute
print("Elements using flat attribute:")
for element in arr.flat:
    print(element)


Elements using flat attribute:
10
20
30
40


# 5) dtype Attribute - Data Type of Array

- The dtype attribute tells the data type of the elements in the array.

In [12]:
import numpy as np

# Creating a NumPy Array
arr = np.array([1.1, 2.2, 3.3])

# Checking Data Type
print("Data type of array elements:", arr.dtype)


Data type of array elements: float64


# 6) itemsize Attribute - Size of One Element in NumPy Array

- The itemsize attribute returns the size (in bytes) of one element in the array.

In [13]:
import numpy as np

# Creating a NumPy Array
arr = np.array([1, 2, 3])

# Finding item size
print("Size of one element:", arr.itemsize, "bytes")


Size of one element: 4 bytes


# 7) flags Attribute - Memory Layout of Array

In [14]:
import numpy as np

# Creating a NumPy Array
arr = np.array([10, 20, 30])

# Checking Memory Layout
print("Memory layout information:")
print(arr.flags)


Memory layout information:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [15]:
import numpy as np
narray = np.array([1,2,3])
for x in narray:
    print(x)


1
2
3


In [16]:
#In a 2-D array it will go through all the rows.
array2 = np.array([[1,2,3],[4,5,6]])
for x in array2:
    print(x)

[1 2 3]
[4 5 6]


In [17]:
n_array = np.array([1, 2, 3], ndmin = 5)
for x in n_array:
    print(x)


[[[[1 2 3]]]]


In [18]:
#Iterating Arrays Using nditer()
#The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration.
n_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(n_array):
  print(x)



1
2
3
4
5
6
7
8
