# Sorting in NumPy Arrays

In [1]:
#Sorting means putting elements in an ordered sequence.
#Ordered sequence, here is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
#The NumPy ndarray object has a function called sort(), that will sort a specified Array.
import numpy as np
array_n = np.array([3,2,0,1])
print(np.sort(array_n))



[0 1 2 3]


In [2]:
#This method returns a copy of the array, leaving the original array unchanged.

In [3]:
#We can also sort arrays of strings, or any other data type
array2 = np.array(['banana', 'cherry', 'apple'])
print([np.sort(array2)])


[array(['apple', 'banana', 'cherry'], dtype='<U6')]


In [4]:
#Sort a Boolean NumPy Array
array_p = np.array([True, False, True])
print(np.sort(array_p))

[False  True  True]


In [5]:
#If you use the sort() method on a 2-D array, both arrays will be sorted.
array_z = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(array_z))

[[2 3 4]
 [0 1 5]]
