# Joining the NumPy Arrays

- Joining NumPy Arrays means combining two or more arrays into a single array.

- In NumPy, joining can be done along different axes (rows or columns).

- Joining allows you to:

- Merge data from multiple arrays.

- Combine arrays along rows or columns.

- Perform advanced matrix operations.


# Joining Using np.concatenate()

- The np.concatenate() method joins two or more arrays along a specified axis.

# 1) Joining 1-D Arrays Using np.concatenate()

In [1]:
import numpy as np

# Creating two 1-D Arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Joining arrays using np.concatenate()
result = np.concatenate((arr1, arr2))

# Printing Result
print("Joined Array:", result)


Joined Array: [1 2 3 4 5 6]


# 2) Joining 2-D Arrays Using np.concatenate()

In [2]:
import numpy as np

# Creating two 2-D Arrays
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

# Joining along rows (axis=0)
result = np.concatenate((arr1, arr2), axis=0)

# Joining along columns (axis=1)
result2 = np.concatenate((arr1, arr2), axis=1)

# Printing Results
print("Joined along Rows:\n", result)
print("\nJoined along Columns:\n", result2)


Joined along Rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Joined along Columns:
 [[1 2 5 6]
 [3 4 7 8]]


# Joining Using np.stack()

- np.stack() joins arrays along a new axis.

# Joining Using np.stack()

In [3]:
import numpy as np

# Creating two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stacking the arrays along a new axis
result = np.stack((arr1, arr2), axis=0)

# Printing Result
print("Stacked Array:\n", result)


Stacked Array:
 [[1 2 3]
 [4 5 6]]


# Joining Using hstack() and vstack()

- hstack() → Join arrays horizontally (column-wise).

- vstack() → Join arrays vertically (row-wise)

In [4]:
import numpy as np

# Creating two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Joining Horizontally
result_h = np.hstack((arr1, arr2))

# Joining Vertically
result_v = np.vstack((arr1, arr2))

print("Horizontal Stack:", result_h)
print("Vertical Stack:\n", result_v)


Horizontal Stack: [1 2 3 4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]


# Joining Using dstack() (Depth Stack)

- dstack() stacks arrays along the depth (3rd dimension).

- Useful for image processing.

In [5]:
import numpy as np

# Creating two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Joining along depth
result = np.dstack((arr1, arr2))

print("Depth Stack:\n", result)


Depth Stack:
 [[[1 4]
  [2 5]
  [3 6]]]


# Attributes Associated with Joining NumPy Arrays

# 1) shape Attribute (Shape of Joined Array)


In [6]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.concatenate((arr1, arr2))

# Checking the Shape
print("Shape of Joined Array:", result.shape)


Shape of Joined Array: (6,)


# 2) ndim Attribute (Number of Dimensions)

In [7]:
print("Number of Dimensions:", result.ndim)


Number of Dimensions: 1


# 3) size Attribute (Total Number of Elements)

In [8]:
print("Total Elements:", result.size)


Total Elements: 6


# 4) dtype Attribute (Data Type of Elements)

In [9]:
print("Data Type:", result.dtype)


Data Type: int32
