# Reshaping the NumPy Array

- Reshaping in NumPy means changing the shape (or dimensions) of an existing NumPy array without changing its data.

- In simple words, you can change the number of rows, columns, or dimensions of an array while keeping all the elements the same.



# Features of Reshaping NumPy Arrays

# 1)  Flexible Shape Transformation

- We can transform arrays between 1D, 2D, 3D, or higher dimensions as long as the total number of elements matches.

In [4]:
import numpy as np
# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape 1D to 2D
reshaped_2d = arr.reshape(2, 3)

# Reshape 1D to 3D
reshaped_3d = arr.reshape(2, 1, 3)

print("1D to 2D:\n", reshaped_2d)
print("\n1D to 3D:\n", reshaped_3d)


1D to 2D:
 [[1 2 3]
 [4 5 6]]

1D to 3D:
 [[[1 2 3]]

 [[4 5 6]]]


# 2) Auto-dimension Calculation with -1.

- Using -1 lets NumPy automatically calculate the appropriate dimension.

In [5]:


# Automatically calculate the number of rows
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(-1, 3)  # Auto-calculate rows

print("Auto-calculated Reshaped Array:\n", reshaped)


Auto-calculated Reshaped Array:
 [[1 2 3]
 [4 5 6]]


# 3) Reshaping is Non-destructive

- .reshape() returns a new array; it does not modify the original array.

In [6]:

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)

print("Original Array:\n", arr)
print("\nReshaped Array:\n", reshaped)


Original Array:
 [1 2 3 4 5 6]

Reshaped Array:
 [[1 2 3]
 [4 5 6]]


# 4) Order Control with order Parameter


- The .reshape() method offers different orders for reshaping:

- order='C' (Row-wise — default)

- order='F' (Column-wise)

- order='A' (Any order, based on memory layout)

In [7]:


arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape in 'C' order (Row-wise - Default)
reshaped_C = arr.reshape(2, 3, order='C')

# Reshape in 'F' order (Column-wise)
reshaped_F = arr.reshape(2, 3, order='F')

print("Reshaped in 'C' Order:\n", reshaped_C)
print("\nReshaped in 'F' Order:\n", reshaped_F)


Reshaped in 'C' Order:
 [[1 2 3]
 [4 5 6]]

Reshaped in 'F' Order:
 [[1 3 5]
 [2 4 6]]


# 5) .reshape() Can Handle Empty Arrays

- An empty array can still be reshaped if dimensions are compatible.

In [8]:
arr = np.array([])  # Empty Array
reshaped = arr.reshape(0, 3)

print("Empty Array Reshaped:\n", reshaped)

Empty Array Reshaped:
 []


# 1) Reshape 1D Array to 2D Array

In [9]:
import numpy as np

# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping to 2D (2 Rows, 3 Columns)
new_arr = arr.reshape(2, 3)

print("Original 1D Array:")
print(arr)

print("\nReshaped 2D Array:")
print(new_arr)


Original 1D Array:
[1 2 3 4 5 6]

Reshaped 2D Array:
[[1 2 3]
 [4 5 6]]


# 2) Reshape 1D Array to 3D Array

In [10]:
import numpy as np

# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape to 3D Array (2 Layers, 1 Row, 3 Columns)
new_arr = arr.reshape(2, 1, 3)

print("Reshaped 3D Array:")
print(new_arr)


Reshaped 3D Array:
[[[1 2 3]]

 [[4 5 6]]]


# 3) Reshape 2D Array to 1D Array (Flattening)

In [11]:
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape 2D Array to 1D Array
new_arr = arr.reshape(-1)

print("Flattened 1D Array:")
print(new_arr)


Flattened 1D Array:
[1 2 3 4 5 6]
